### ISSUE TITLE
TODO: Make Steam Directly Useful

### ISSUE THREAD

**Issue by LemmaEOF** [elytra/BetterBoilers#7]
Now that steam creation is pretty much All Good except for alternate sources (which are under progress; one alt source is awaiting a mod upload to Maven and the other is awaiting a Forge PR) and improved scanning code, I feel that I should add steam turbines/pistons/whatnot to make steam DIRECTLY useful without having to depend on another mod!
What needs to be thought about:
- [x] What should the generation calculations be? How should the multiblock affect the calculations?
- [x] What parts should the generator multiblock have?
- [x] What material should the parts be made out of?
- [x] What constraints should the multiblock have?

**Comment by LemmaEOF** [comment]
Thoughts on tickbox 1:
- Number of turbines affects fueltick rate, kinda like how fireboxes affect fueltick rate?
- 80 rf/fueltick, fuelticks/gametick rate varies
- more turbines = faster steam consumption, naturally
- possibly diminishing returns for having multiple turbines? Otherwise way too easy to get ultrahigh rf/t without much risk
- steam:RF ratio is universally 2RF:1mB, so need to up steam production rate accordingly if I want good coal efficiencies
- Typical rf/coal values are 32k-48k, so maybe having 64k/72k per coal through steam might be good
- if 2 rf from 1 mb steam, that would be 32/36 buckets of steam per coal
- Thermal Expansion dynamos w/ boiler conversion give ~27B so yeah that's about right
- 32/8 = 4 buckets per cycle, or 36/8 = 4.5 buckets per cycle
- 80 rf/fueltick = 40 steam/fueltick
- If 32 buckets per coal, have to slow the boiler *way* down, including coal burn rate

**Comment by deli73** [comment]
maybe we could add a few component parts, like Thermal Expansion has but a tad less needlessly complicated?

**Comment by deli73** [comment]
i'm no good with "balancing" so i can't help with that much

**Comment by LemmaEOF** [comment]
That's ok! I just need generals idea for now, I can crunch numbers to get a good balance myself.

**Comment by LemmaEOF** [comment]
Alright, I think I've got a good idea for tickbox 1. Now for the rest of the thing: how should the multiblock be shaped? Ideas:
- typical rectillinear thing, blocktype A for border, blocktype B for walls, turbines or other blocks inside
- more free-form thing like advanced generators
- something else? I really need help coming up with something interesting for this

**Comment by LemmaEOF** [comment]
Turbines are almost 100% done!! Just waiting on a couple textures from @insomniakitten and it's ready to release!
